export const SIGNUP_REQUEST = "SIGNUP_REQUEST";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAILURE = "SIGNUP_FAILURE";

export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const LOGOUT_REQUEST = "LOGOUT_REQUEST";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAILURE = "LOGOUT_FAILURE";

export const USER_TOKEN = "USER_TOKEN";

export const GET_SERVICE_REQUEST = "GET_SERVICE_REQUEST";
export const SERVICE_REQUEST_RESPONSE = "SERVICE_REQUEST_RESPONSE";
export const SERVICE_REQUEST_ERROR = "SERVICE_REQUEST_ERROR";
export const ADD_SERVICE_REQUEST = "ADD_SERVICE_REQUEST";
export const UPDATE_SERVICE_REQUEST = "UPDATE_SERVICE_REQUEST";

export const USERS_LIST_REQUEST = "USERS_LIST_REQUEST";
export const USERS_LIST_RESPONSE = "USERS_LIST_RESPONSE";
export const USERS_LIST_ERROR = "USERS_LIST_ERROR";
export const INITIALDATA_FETCHED = "INITIALDATA_FETCHED";